[project]
name = "hw-seckill"
version = "0.1.0"
description = "Add your description here"
readme = "README.md"
requires-python = ">=3.12"
dependencies = [
    "configparser~=6.0.0",
    "loguru~=0.7.2",
    "requests~=2.32.4",
    "selenium==4.15.1",
    "webdriver-manager==4.0.0",
]
